### ISSUE TITLE
OMI BRO restructure TAI93 time

### ISSUE THREAD

**Issue by nlenssen2013** [podaac/l2ss-py#106]
I am integrating dataset OMBRO_003. This dataset doesn't have TAI93 in the unit's attributes the way OMSO2_003 does. Like OMSO2, xarray does not decode times for OMBRO so for temporal subsetting to execute the origin of the time variable in seconds must be determined

**Comment by nlenssen2013** [comment]
If tai93 description is not available in the variable attributes - use utc_start time

**Comment by frankinspace** [comment]
There's not a whole lot of information here. Can you explain what it is you're trying to do?

Something along the lines of: I am integrating dataset **X** with l2ss-py. This dataset is structured like **Y** which does not currently work with the logic in l2ss-py because **Z**.

**Comment by nlenssen2013** [comment]
> There's not a whole lot of information here. Can you explain what it is you're trying to do?
> 
> Something along the lines of: I am integrating dataset **X** with l2ss-py. This dataset is structured like **Y** which does not currently work with the logic in l2ss-py because **Z**.

updated
