### ISSUE TITLE
Expanded Time

### ISSUE THREAD

**Issue by nlenssen2013** [podaac/l2ss-py#11]
TROPOMI products that have "time" and "delta_time" will have delta time to be the same shape as lat/lon. In the current get_time_variable method, if variable contains "time" that variable will get the squeeze() method and the lat/lon variable will not get .squeeze()

**Comment by j-m-adams** [comment]
nlenssen2013 and I are testing this code change:

@@ -486,10 +487,10 @@ def get_time_variable_name(dataset, lat_var):
         return time_vars[0]

     for var_name in list(dataset.dims.keys()):
-        if "time" in var_name and dataset[var_name].squeeze().dims == lat_var.dims:
+        if "time" in var_name and dataset[var_name].squeeze().dims == lat_var.squeeze().dims:
             return var_name
     for var_name in list(dataset.data_vars.keys()):
-        if "time" in var_name and dataset[var_name].squeeze().dims == lat_var.dims:
+        if "time" in var_name and dataset[var_name].squeeze().dims == lat_var.squeeze().dims:
             return var_name
     raise ValueError('Unable to determine time variable')
