### ISSUE TITLE
Include subsetting for variables in top group without a slash

### ISSUE THREAD

**Issue by nlenssen2013** [podaac/l2ss-py#126]
Earthdata search doesn't show variables that are in the top level of a file with grouped data. This is because there is a leading slash in front of these variables and won't show them. Fix is to make the code more flexible to variables without the leading 
(https://search.uat.earthdata.nasa.gov/projects?p=C1232998567-GES_DISC!C1232998567-GES_DISC&pg[1][a]=1242124279!GES_DISC&pg[1][v]=t&pg[1][gsk]=-start_date&pg[1][m]=harmony0&pg[1][ets]=t&q=SNDR&tl=1668529855!3!!)

https://bugs.earthdata.nasa.gov/browse/GDDS-459

**Comment by nlenssen2013** [comment]
> I don't think this is an issue with l2ss-py. If I recall correctly Harmony takes care of normalizing the variable names passed to backend services. Will need to confirm with Harmony team first though.

But the variable names in UMM-VAR need to be altered, won't that mean l2ss-py will need to accommodate that?

**Comment by frankinspace** [comment]
Looks like I was mistaken and that Harmony just sends whatever is in UMM-V for variable name.
However, I still don't know what the ask is on the l2ss-py side of things?

**Comment by nlenssen2013** [comment]
To be flexible with a given variable in the root group without a front slash. Variable subsets for SNDR should be able to work for "/surf_temp" and "surf_temp"
