### ISSUE TITLE
Add support for granules where time variable represents lines

### ISSUE THREAD

**Issue by skorper** [podaac/l2ss-py#24]
An example of this would be `SWOT_SIMULATED_L2_KARIN_SSH_ECCO_LLC4320_CALVAL_V1`, (`C2158344213-POCLOUD`), which has the following structure

```
>>> ds.time
<xarray.DataArray 'time' (num_lines: 9866)>
array(['2011-11-13T07:43:01.639593984', '2011-11-13T07:43:01.954040000',
       '2011-11-13T07:43:02.268488000', ..., '2011-11-13T08:34:27.435267968',
       '2011-11-13T08:34:27.751033984', '2011-11-13T08:34:28.066801024'],
      dtype='datetime64[ns]')
Coordinates:
    latitude_nadir   (num_lines) float64 ...
    longitude_nadir  (num_lines) float64 ...
Dimensions without coordinates: num_lines
Attributes:
    long_name:           time in UTC
    standard_name:       time
    leap_second:         YYYY-MM-DDThh:mm:ssZ
    comment:             Time of measurement in seconds in the UTC time scale...
    tai_utc_difference:  34.0
>>> ds.coords
Coordinates:
    latitude         (num_lines, num_pixels) float64 ...
    longitude        (num_lines, num_pixels) float64 ...
    latitude_nadir   (num_lines) float64 ...
    longitude_nadir  (num_lines) float64 ...
```

**Comment by skorper** [comment]
This same issue has been observed in collections `OS2_OSCAT_LEVEL_2B_OWV_COMP_12_V2`, `QSCAT_LEVEL_2B_OWV_COMP_12_KUSST_LCRES_4.1`, and `QSCAT_LEVEL_2B_OWV_COMP_12_LCR_3.1`

**Comment by j-m-adams** [comment]
Also appears in several GES DISC collections, e.g. S5P_L2__CH4____HiR 1 (C1627516288-GES_DISC) , that has these coordinates:
```
/PRODUCT/scanline        {3245}
/PRODUCT/ground_pixel    {215}
/PRODUCT/time            {1}
/PRODUCT/delta_time      {1, 3245}
/PRODUCT/latitude        {1, 3245, 215}
/PRODUCT/longitude       {1, 3245, 215}
```

**Comment by skorper** [comment]
This needs to be tested with `SWOT_SIMULATED_L2_KARIN_SSH_ECCO_LLC4320_SCIENCE_V1` as well.

**Comment by skorper** [comment]
The full list of SWOT collections this is causing errors for is:

- `SWOT_SIMULATED_L2_KARIN_SSH_GLORYS_CALVAL_V1 `
- `SWOT_L2_LR_SSH_Expert_001_001_20140412T120000_20140412T125126_DG10_01 `
- `SWOT_SIMULATED_L2_KARIN_SSH_ECCO_LLC4320_SCIENCE_V1 `
- `SWOT_SIMULATED_L2_KARIN_SSH_ECCO_LLC4320_CALVAL_V1 `

**Comment by skorper** [comment]
The following SMAP SSS collections also have this issue: 

- `SMAP_JPL_L2B_NRT_SSS_CAP_V5`
- `SMAP_JPL_L2B_SSS_CAP_V5`
