### ISSUE TITLE
Accept a boolean from Harmony to set `cut=` parameter when run as part of service chain

### ISSUE THREAD

**Issue by danielfromearth** [podaac/l2ss-py#247]
We've been tracking down a [newly discovered bug](https://github.com/danielfromearth/stitchee/issues/118#issue-2172403683) that occurs when running the l2ss>Batchee>StitchEE>CONCISE chain in UAT.

It seems like the unexpected condition may have been hidden because of a discrepancy in arguments being passed to L2SS's high-level `subset()`  function, between command-line invocations and Harmony invocations... `cut=False` by default [in the cli](https://github.com/podaac/l2ss-py/blob/61a581512fec3f94d10cd1b903d5f99fd4adf141/podaac/subsetter/run_subsetter.py#L67); and [no argument is given in the Harmony adapter](https://github.com/podaac/l2ss-py/blob/61a581512fec3f94d10cd1b903d5f99fd4adf141/podaac/subsetter/subset_harmony.py#L174) so it uses the default of `cut=True` [in the function definition](https://github.com/podaac/l2ss-py/blob/61a581512fec3f94d10cd1b903d5f99fd4adf141/podaac/subsetter/subset.py#L1121).

In effect, I think l2-subsetter services have been  (and probably want to continue)  using `cut=True`, but for the batchee>stitchee>concise chain, we want `cut=False`.

It seems like to address this we might need a service- (or collection-) specific argument/configuration to be passed from Harmony to L2ss-py.

**Comment by frankinspace** [comment]
Previous discussions about this feature can be found in
https://bugs.earthdata.nasa.gov/browse/PCESA-1528
https://bugs.earthdata.nasa.gov/browse/TRT-22
https://bugs.earthdata.nasa.gov/browse/TRT-13
