### ISSUE TITLE
As a Harmony service, I want to use coordinate variable information to identify coordinates when available

### ISSUE THREAD

**Issue by frankinspace** [podaac/l2ss-py#77]
If a collection contains UMM-V associations where the UMM-V is identified as `VariableType: Coordinate`, that information will be passed to l2ss-py as part of the dataOperation message.

l2ss-py should be improved to use this (optional) information if it exists in order to more accurately identify which variables in the collection should be used as coordinates.

Relates to: https://bugs.earthdata.nasa.gov/browse/TRT-159

Acceptance Criteria:
- L2SS updates subsetting processing logic to utilize UMM-Var information.
- Subsetted outputs from L2SS remain unchanged compared to outputs from hardcoded coordinate metadata handling.

**Comment by skorper** [comment]
This is in production, closing.
